// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omhfdmbnxdcywcwpgoke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9taGZkbWJueGRjeXdjd3Bnb2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU4MTYxNDgsImV4cCI6MjA4MTM5MjE0OH0.uHHv1oeXsK6q4teb2Z8YMO4W81Mho0SJonlJW_hysDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});